### PR TITLE
Instantiate basic mkdocs site with GH pages

### PR DESCRIPTION
**Pull request by penelopeysm**
This PR generates a little [mkdocs](https://www.mkdocs.org/) site (in `docs/`, config is `mkdocs.yml`) and adds a GitHub Action to build the pages and deploy to GitHub Pages.

@andrewphilipsmith I know we discussed this before and I can't remember if you mentioned you preferred readthedocs over GH pages? I'm not sure if there are practical differences (and if so what they are!) but let me know if you'd rather deploy to rtd as it should be a fairly easy switch. This is a tiny PR 😉

### CODE REVIEW

**Comment by andrewphilipsmith** [comment]
@penelopeysm Sorting out the docs is long overdue, so thank you for doing this.

I am persuadable, but I do prefer RTD in most cases.

**Slightly objectively:**
Anecdotally - a big generalisation, but on previous projects, I've found:
* Hosting on GH pages seems to result in a steady stream of maintenance tasks of needing to fix the rendering of the docs.
* RTD tends to be a case of set-it-and-forget-it.
I'm sure others have different experiences.

Also hosting the docs is not a core part of the project, so I am happy to outsource it, and just focus on writing them.


**Personally:**
I dislike reading and writing prose in fixed-width fonts. I find it tiring and difficult to spot errors. I find using a code editor to write prose unwieldy - anything more than a couple of sentences I will open up word/google docs etc and cut and paste the result back into the markdown docs as required. (I know this makes me an anomaly in REG, but 2.5 years in I am more convinced of this, not less.)

As a result, I find git diffs of prose pretty much useless, and I always want to compare rendered versions of the docs. Comparing the rendered docs at different points in the git history, is possible with local clones of GH pages docs, but it is a bit of a faff. It is made very easy in RTD.

**Comment by andrewphilipsmith** [comment]
If we do go for mkdocs, then the `docs` section in `[project.optional-dependencies]` in `pyproject.toml`, should be updated to reflect this. In other aspects, looks good to me.

**Comment by penelopeysm** [comment]
@andrewphilipsmith Thanks for explaining. Diffs are a great shout!

The built docs for this PR are now at https://popgetter--107.org.readthedocs.build/en/107/. If we merge into main it should then give us a nicer URL. As a note to myself, I think I might need to then add you all as admins for the project on RTD.

**Comment by penelopeysm** [comment]
Will merge this so that other PRs don't have ugly red ticks 😄

**Pull request merged**
