### PR TITLE
Upgrade pydantic->2.7; update metadata schema

### LINKED ISSUE #81: Enhancing metadata with info required for programmatic traversal
As I understand it, for **Belgium** there is currently:

- geometries at various levels (in decreasing size: region, province, administrative district, municipality, submunicipality, statistical sector)
- population data at _municipality_ level, the second-smallest division

This data and metadata is fine for a human to look through and use, but cannot be traversed in a programmatic way just yet.
In this issue I'll describe what's lacking, and make some suggestions for what to change to make it possible.

I expect the points raised here to be relevant to all countries.
Thus, although I'm contextualising them using the Belgian data, the changes will affect the overall metadata schema and should be applied to every country we provide in popgetter.

I'm not sure how helpful it is, but in case you wish to see what my work, I threw together some Python scripts. Note that of these scripts, only (1) will run with the code on popgetter main branch as (2) and (3) rely on local changes.

1. [Plot the population per municipality given the current format of the data.](https://gist.github.com/yongrenjie/5fbb2f200518a2c663d203e853a7a549#file-1_process_from_current-py) You will see that this script requires a few 'magic constants', which is what is preventing us from traversing the data programmatically.
2. [Restructure the data according to the changes I propose below](https://gist.github.com/yongrenjie/5fbb2f200518a2c663d203e853a7a549#file-2_restructure_belgium_data-py)
3. [Plot the population per municipality given the restructured data.](https://gist.github.com/yongrenjie/5fbb2f200518a2c663d203e853a7a549#file-3_process_from_restructured-py) This script doesn't need any 'magic constants' beyond the fixed filepaths for metadata parquets, and the column names of the deserialised structs. For the CLI library, we would essentially be porting this code to Rust.

## 1. The `SourceDataRelease` itself

The `SourceDataRelease` here

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/assets/be/census_tables.py#L41-L54

is present in the popgetter library, but is not exported as an asset in Dagster.
This needs to be made available.

## 2. Metadata for geometry file

In the `GeoDataFrame` exported by Dagster, there are several columns. The most important of these are the IDs of each geographic subdivision:

 - `cd_sector` (statistical sector)
 - `cd_sub_munty` (submunicipality)
 - `cd_munty_refnis` (municipality)
 - `cd_dstr_refnis` (administrative district)
 - `cd_prov_refnis` (province)
 - `cd_region_refnis` (region)

and their names. Each geography level has three columns for the names in Dutch, French, and German.

 - `tx_sector_descr_{nl,fr,de}`
 - `tx_sub_munty_{nl,fr,de}`
 - `tx_munty_descr_{nl,fr,de}`
 - `tx_adm_dstr_descr_{nl,fr,de}`
 - `tx_prov_descr_{nl,fr,de}`
 - `tx_rgn_descr_{nl,fr,de}`

The `SourceDataRelease` tells us that the population data is provided at municipality level.
However, when the programme reads this in, it cannot identify which columns of the `GeoDataFrame` it should look up the municipality IDs and names from.

The geometries must thus be enriched with some kind of metadata which _looks like_:

```json
[
  {
    "level": "municipality",
    "id": "cd_munty_refnis",
    "name": ["tx_munty_descr_nl", "tx_munty_descr_fr", "tx_munty_descr_de"]
  },
  {
    "level": "administrative_district",
    "id": "cd_dstr_refnis",
    "name": ["tx_adm_dstr_descr_nl", "tx_adm_dstr_descr_fr", "tx_adm_dstr_descr_de"]
  },
  (...)
]
```

That way when the programme sees `municipality` in the `SourceDataRelease` it knows that the IDs can be found in `cd_munty_refnis`, and that there are three names for it in those respective columns.

Going one step further: to _tie_ this metadata to the geometries themselves, what we could do is to define a new type for geometry data:

```python
class GeographyRelease(BaseModel):
    name: str
    date_published: datetime.date
    # ^ Plus any other info we want to include...
    filepath: str   # could be multiple paths for different output formats

class GeographyReleaseLevel(BaseModel):
    release_name: str        # name of the above
    level_name: str          # "municipality"
    code_column: str         # "cd_munty_refnis"
    name_columns: list[str]  # ["tx_munty_descr_" + s for s in ["nl", "fr", "de"]]
```

Then the `SourceDataRelease`, instead of referring to a `geography_file` and `geography_level`, would refer to a `geography_release_name` and `geography_level_name`.

### 3. All nested types should be stored as IDs OR primary keys instead of the types themselves

This includes
 - `SourceDataRelease.publishing_organisation`
 - `SourceDataRelease.countries_of_interest`
 - `DataPublisher.countries_of_interest`
 - possibly anything else I missed

There are two reasons for this.
1. Storing them as the types themselves leads to duplication of information. This means:
   - querying will require the transmission of more data than needed
   - having the same object defined multiple times this can possibly lead to data inconsistency
2. They can't be serialised as parquet files 😢  `df.to_parquet()` will throw an error saying 'did not recognize Python value type when inferring an Arrow data type'.

To fix this, we need to assign each class instance a unique ID **or** ensure that they have a unique field, and store the value of that instead of the full type itself.

My personal inclination is that instead of trying to generate a unique ID for each `SourceDataRelease` (etc), it is easier to use the name as a primary key and look them up by name:
 - instead of storing `source_data_release_id` we store `source_data_release_name`
 - we have to ensure that `source_data_release_name` is unique between all `SourceDataRelease`s

This is, in my opinion, better than using IDs because generating unique, reproducible IDs is quite nontrivial:
 - `uuid4()` gives different results each time the pipeline is run and so is not reproducible. Say for example someone uses the CLI to fetch a metric with a given UUID — this is a very natural operation to do if the user already knows what they want. But if we rerun the pipeline or update the data then that UUID will be invalidated and their workflow will break.
 - if we use a counter as the ID we have to make sure that there are no clashes.
   This is OK if we are inserting into a database because we can set a column to autoincrement, but in Python we would have to use some kind of global variable,
   and the final result would depend on the order of execution as well as which assets are materialised, and that's very ugly.
 - if we construct some kind of hash from the fields, a unique hash necessitates having unique field(s), so why not just use the unique field as the key instead.

### 4. Data tables need to have the geoid column set as the index

This isn't an issue because it's already true for Belgium, but it's something that we need to be cognisant of.
It can't just be an ordinary column in the dataframe because then the CLI will need to know which column to pick up the IDs from.

----------------------

# Overall, what does each country need to export?

If we go with the suggestions above, then each country's pipeline should output the following:

 - (dataframe) **A list of `GeographyRelease`s**

   There can be multiple of these because we may have, say, 2011 and 2021 census data for the UK where the boundaries are different.

   - (various output formats) **Geometry files**

     Each `GeographyRelease` will point to the file(s) containing the geometries.

 - (dataframe) **A list of `GeographyReleaseLevel`s**

 - (dataframe) **A list of `MetricMetadata`s**

   This would enumerate all data that are available and tell the programme where to find them.

   - (parquet) **Data files**

     Each `MetricMetadata` will point to the file containing the data (in parquet format).

 - (dataframe) **A list of `SourceDataRelease`s**

 - (dataframe) **A list of `DataPublisher`s**

 - (dataframe) **A `CountryMetadata`**

Because the five dataframes all refer to each other, I do feel like it is _natural_ to store them in a relational database.
In this case, a single database will need to be exported with a standardised filename, and the table names should also be standardised.
_However_, as Stuart pointed out, this will likely cause issues compiling to WASM:
 - it seems the maintainers of the `duckdb-rs` library have no intention of supporting WASM (https://github.com/duckdb/duckdb-rs/issues/56)
 - rusqlite is more interested in doing it, and there's an PR for it, but hasn't been merged (https://github.com/rusqlite/rusqlite/pull/1010)

**So for now, I'd suggest that we export them as separate (parquet?) files.**
In this case they will all need to have predefined and standardised filenames.
Alternatively, we could have one single top-level file for each country (say `be/info.json`) which points to the five files.

---------------

# Going forward

I'd really appreciate any comments or suggestions on the above.
I think the _issues_ that I've pointed out are not subjective --- they're things that we _will_ need to fix.
However, it's very conceivable that there may be better ways to fix them than what I've suggested above!
I've tried to be opinionated on this just so that we have something concrete to talk about.

Once we reach a consensus, I'm totally happy to make necessary changes on this repo as well.
(I have already done some of them locally so that my script can run.)

### LINKED ISSUE #83: Generating IDs for metadata structs
## Context

In Wednesday's meeting we resolved to use a normalised, non-nested schema to represent the metadata.

This means that each struct needs to have a unique string to use as an ID. This string should be constructed from a set of fields which uniquely identify it.

This issue is to let us decide:
 - which fields uniquely identify each struct
 - how they should be combined

My proposals are as follows:

----------------------------

### `CountryMetadata`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L9-L17

**Suggestion**

Add `iso3166_2` field (this is required for e.g. Scotland and is included as part of #58)

Use `iso3166_2` as the identifier if present. If `iso3166_2` is None, then use `iso3`

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/867b764e963ff4768d8f6daac9d88346f2a32eae/python/popgetter/metadata.py#L9-L14

-----------------------------

### `DataPublisher`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L20-L28

**Suggestion**

Use `name` as the identifier

-----------------------------

### `SourceDataRelease`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L31-L63

**Suggestion**

In the meeting we said that these should be identified by a tuple of (name, geographic level, year). I've implemented this as a PR in #81:

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/44e5a4d53b0478d20268bdb7d0cf40ae5fb6e21e/python/popgetter/metadata.py#L33-L40

-----------------------------

### `MetricMetadata`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L66-L112

**Suggestion**

I think this one is the one I'm least certain about. Right now, in #81 I've opted to combine the `source_data_release_id` (which would in turn contain the three fields above) and the HXL tag.

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/44e5a4d53b0478d20268bdb7d0cf40ae5fb6e21e/python/popgetter/metadata.py#L69-L77

In place of the HXL tag, I could equally see us using either:
 - the human-readable name (problem: this might end up being really quite long)
 - the parquet column name (problem: this might not be unique if there are multiple parquet files belonging to the same source data release)

Which of these is the best?

### PR DESCRIPTION
**Pull request by yongrenjie**
Closes #81

Closes #83

This PR:

- updates the metadata schema as discussed at various meetings. Specifically:
  - references to nested data structures have been changed to just their identifiers
  - the reference period and collection period date tuples in `SourceDataRelease` have been separated out into two different fields
  - `DataPublisher`, `SourceDataRelease`, and `MetricMetadata` now have an `id` property which is computed from a set of its fields. This means that you don't have to construct the ID yourself when instantiating the class, but the ID will still be included in the serialisation. For these three classes, the ID is calculated by serialising all other instance variables to JSON and calculating a SHA256 hash.
  - `CountryMetadata` has an ID which is simply `iso3166_2` if present and `iso3` otherwise.

- makes minor modifications to Belgium code to use the updated schema

- adds a Markdown file (`output_spec.md`) to specify how the outputs for each country are to be arranged when uploaded

- upgrades the version of pydantic to v2.7 to make use of the `@computed_field` decorator

    - It's possible to accomplish the same thing with pydantic v1, but rather messier. I've tested pydantic 2.7.1 with BE, UK, and 10 partitions of the US data, all of them materialise fine. (It seems that support for Pydantic 2 was added in October last year: https://github.com/dagster-io/dagster/issues/15162)

- reincorporates changes to the JSON schema export function made in #80 

---------

## Still to be done before this should be merged

- [x] Settle on the set of fields which need to go into the identifiers (#83)
- [x] Settle on the function to generate the identifiers from those fields
- [x] Fix CI errors

### CODE REVIEW

**Comment by sgreenbury** [comment]
Noting that [output_spec.md](https://github.com/Urban-Analytics-Technology-Platform/popgetter/pull/82/files#diff-500368661d562014566f1959d68c1b430620f41b64198d3655c6cae9d3785de5) to be used in #75

**Comment by stuartlynn** [comment]
This looks good to me. A couple of comments in the code. @yongrenjie can you generate the schema file for this so we can check it has everything we need. The last one had some missing properties and some which where in the required list but shouldn't have been. We might as well use this PR to tidy up those issues as well. Some of those changes I made manually here: https://github.com/Urban-Analytics-Technology-Platform/popgetter-cli/pull/19/files#diff-299f088d3756b6e82522f491911bf9a739548adc6bbde0f60fe7d4b22f105ed2R164-R283

**Comment by yongrenjie** [comment]
@stuartlynn looking at the changes you made, we could make `source_download_url` and `source_documentation_url` optional.

But we need one (and ideally only one) of `MetricMetadata.source_data_release_id` or `SourceDataRelease.available_metrics` to tie the metrics to the releases. My preference would be to use the former, which is what this PR would generate.

I don't see your comments in the code! 😓

**Comment by yongrenjie** [comment]
(Maybe @andrewphilipsmith you have thoughts on the above?)

**Comment by stuartlynn** [comment]
> @stuartlynn looking at the changes you made, we could make `source_download_url` and `source_documentation_url` optional.
> 
> But we need one (and ideally only one) of `MetricMetadata.source_data_release_id` or `SourceDataRelease.available_metrics` to tie the metrics to the releases. My preference would be to use the former, which is what this PR would generate.
> 
> I don't see your comments in the code! 😓

Hey sorry I meant couple of comments on the PR inline with the code (jn this thread) 

Yeah that sounds good about having just the source_data_release_id. I think that works better with the new model.

**Comment by sgreenbury** [comment]
Looks good to me! As discussed, one thought is it might be worth including a test for the hashing process for IDs using an example metadata instance and then testing it deterministically produces the same ID for the same metadata and different IDs for different metadata.

**Pull request merged**
